common:
  n_runs: 10
  n_episodes: 200
  n_steps: 1000
env:
  env_id: ConstStepFourrooms-v0
agent:
  name: DTAAgent
  raw_agent: SarsaAgent
shaping:
  subgoal_path: fourroom/in/subgoals/fourrooms_minimum_subgoals.csv
  vid: table
  aggr_id: dta
  range: 0

